### ISSUE TITLE
Write authors of How do LLMs handle multilinguality?

### ISSUE THREAD

**Issue by natriistorm** [intsystems/CreationOfIntelligentSystems_Multilingual_Interpretability#7]

**Comment by natriistorm** [comment]
Не ответили(

**Comment by natriistorm** [comment]
https://github.com/zhaoyiran924/Adv-In-Context-Learning/issues/5 ждем

**Comment by zhaoyiran924** [comment]
Thank you for your interest in our work. We're excited to announce that we've just received permission to open source our project, adhering to our company's data confidentiality policy. Please take a look, and if you have any questions, feel free to contact us.
